### ISSUE TITLE
Can't create a new chapter in a new folder

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/feedback#104]
## Bug Report

I can't see an easy way to create a new chapter in a new folder I name it and sub-chapters should be under the new folder automatically or I specify that  
### What is the current behavior?

Create chapter - the chapter.md file gets created in the root path by default 
Sub-chapters in the root folder too
### What is the expected behavior?

The 5. ex was giving an easy way to specify the "where" when it ask for chapter name
#### For GitBook Editor
- Operating System?

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```
- (Web) Browser version?
- (Desktop) Editor version?

Version 6.1.1
- Was the bug present in previous versions?

Yes
## Good to create an issue template ;)

The GitBook Team

**Comment by nagim** [comment]
Strange, because I have this option on 6.1.1.
When I right-click on a folder and select **New Folder**, it automatically fills in the **Where** field and creates the folder in there. I can also specify it manually.

![image](https://cloud.githubusercontent.com/assets/16205115/17014215/a0bfed0c-4f23-11e6-9f9f-a57eec097582.png)

Works in the file tree and asset manager as well. Win 7 64bit.

**Comment by KINGSABRI** [comment]
It's exsit when create a new file/folder not create a new chapter/sub-chapter

**Comment by nagim** [comment]
Hmm, tested with folders and works the same as I mentioned in my previous post.
