### ISSUE TITLE
Couple of things on new Dashboard

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#148]
Here are things that don't make sense to me.

1. From gitbook.com where you can browse all the books that you have an access to, narrow the search by clicking 'OrgVue' (organisation account) it shows 17 books. However from an organisation account (gitbook.com/@OrgVue), there are only 2 books.  Maybe this is the page for the public where only lists public books. Still I think there should be a sort of distinction between what org member see and what other see.
2. From gitbook.com dashboard, on the right-hand side, the math doesn't sum up, 17+0=18. There should be some sort of clue how it's 18 in total.

![dashboard](https://cloud.githubusercontent.com/assets/14980884/17887747/bf650934-691f-11e6-8bde-0510ef3172ac.png)
![org_dashboard](https://cloud.githubusercontent.com/assets/14980884/17887748/bf657928-691f-11e6-8548-8fd88b3fd856.png)

**Comment by SamyPesse** [comment]
1. The author profile (like https://www.gitbook.com/@orgvue) currently list books which are public and ready. We might change it very soon.
2. The math doesn't sum up because the `All` also list books from other users/orgs where you are a collaborator (currently, there is not filter in the sidebar for this)
