### ISSUE TITLE
Request for Simple Password Protection Instead of Full Authentication

### ISSUE THREAD

**Issue by dustinrjo** [GitbookIO/feedback#241]
## Category

Feature Request

## What is the current behavior?

For private books, every reader of the book needs to have an account registered with gitbook and as an owner of the book I must grant access to each account.

## What is the desired behavior?

Currently I need a private book but I need to share access to it with thousands of people.  I do not need it to be crazy secure, just not fully public, so for my purposes, having nothing more than a simple password in front of it that I can change and share with the 1000+ people would make this a usable platform.  Without this, I have to somehow get every person to sign up for an account with gitbook and then they have to authenticate that way and I have to grant them access.  This is so far from scalable on my end that I will simple have to export all of my markdown to my own static site that I will password protect in this manner when I get time in a few months if this is not a feature that gets added.

## Additional information

I _could_ create a dummy account on gitbook presumably and grant it access and then share the username and password to that dummy account to the 1000+ readers, but this feels wrong.

**Comment by AaronO** [comment]
@dustinrjo This is actually already implemented :) Though I must admit it's not terribly visible (but we've got a change that brings more structure to the preview/share workflow).

So what you want is called **Access Tokens**, you can generate revokable access tokens from your book's settings. You can share these as links to grant access to private content for non-gitbook users.

Does that make sense ?

P.S: closing the issue since it's already implemented (and will be improved in an upcoming UX release)
