### ISSUE TITLE
Change in Open Source Plan :(

### ISSUE THREAD

**Issue by mambax7** [GitbookIO/feedback#307]
## Category

GitBook
## What is the current behavior?

GitBook is trying to force us to "pay-up" for number of contributors and has set the number of private books to 0 for Open Source projects
![image](https://cloud.githubusercontent.com/assets/613686/21964410/63252f16-db19-11e6-9754-af3984169411.png)

## What is the desired behavior?

Leave the constraints as they were before, i.e. 1 free private book, and unlimited number of collaborators for Open Source projects.

**Comment by AaronO** [comment]
Hi Michael,

We are not trying to force open-source orgs to "pay-up" by any means ... 

These checks are a simple safeguard to prevent abuse, whilst unlocking open-source orgs so they can get up and running without having to reach out to our support team. And if they do hit the limits, we're happy to provide them with a 100% discount for a larger plan.

Our pricing changes were made with open-source teams in mind, we wanted to have a plan that specifically targeted them, which is why the first plan is "Open Source".

Send a request through our [Contact page](https://www.gitbook.com/contact) and we'll be happy to provide you with a coupon giving you a 100% discount for a larger plan.

**Comment by mambax7** [comment]
My recommendation: don't remove the 1 private book from Open Source projects, because it's good for testing 
And remove the constraints for collaborators who are on GitHub and who link their books to GitHub repositories, and are members of an Open Source project. 

I sent you a message to you Contact page.
