### ISSUE TITLE
Footnote numbering is not updated on inserting footnotes

### ISSUE THREAD

**Issue by i3games** [GitbookIO/feedback#472]
## Category

Bug in editor

## What is the current behavior?

Write some text. Enter a footnote. Then enter a second footnote above the first one.

The second footnote you entered is numbered 2, the first footnote you entered is 1.

## What is the desired behavior?

The second footnote you entered above should have number 1, the footnote below be number 2. That is, the footnotes should be numbered _in the order of appearance_, not in the order of the point in time  you entered them.
 
## Additional information

Web version, Firefox on Mac

**Comment by AaronO** [comment]
@i3games In markdown footnotes aren't necessarily a linear sequence of numbers, they're basically a label. Which makes sense because people might want to have more descriptive footnote labels.

By default we assume they are linear numbers and automatically fill those in for the user when inserted, but we don't rename/change the labels based on the ordering because we don't have absolute control over that and that the user may have manually edited custom labels.

This is another scenario where it's sometimes hard to have a great out of the box experience for different users, with different needs and expectations.

**Comment by i3games** [comment]
There is no single publication I am aware of that has footnote numbers that are out of order. These are very special cases that people want to have custom markers, but even then the ordering of the footnotes should be top down. It does't make sense.

**Comment by i3games** [comment]
If anyone stumbles over this issue, I created a quick fix [https://github.com/i3games/fix-gitbook-footnotes](https://github.com/i3games/fix-gitbook-footnotes).
