### ISSUE TITLE
cannot get back to editing in preview mode after clicking markdown mode

### ISSUE THREAD

**Issue by EDDYMENS** [GitbookIO/feedback#526]
On clicking markdown mode I cannot seem  to get back to preview edit mode.

**Comment by aroberge** [comment]
This happened to me as well after I inserted some raw html code.

**Comment by EDDYMENS** [comment]
@aroberge same here, I guess thats how its going to be

**Comment by AaronO** [comment]
@EDDYMENS Yep, @aroberge is correct, the WYSIWYG mode doesn't support HTML because it's "impure" (HTML is really ambiguous).

The editor in our new release (private beta: [beta.gitbook.com](https://beta.gitbook.com), supports rich content (rich embeds, alerts/hints, api methods [being implemented], ...) out of the box. So writing raw HTML or the gitbook plugin/templating syntax are no longer necessary, rich content is now a first class citizen :)

@EDDYMENS Would be great to know why you needed to write raw HTML (so maybe we can support that use-case directly in the editor)

**P.S:** Closing this issue since in the new beta there will only be one editor that supports rich content and markdown shortcuts all unified together and fully WYSIWYG.

**Comment by EDDYMENS** [comment]
Interesting in my case it wasn't html it was a markdown. @AaronO

**Comment by AaronO** [comment]
@EDDYMENS Hmmmm, can you share the markdown content here ?

Normally if it's plain markdown that should be supported by the current editor and you should be able to switch back to WYSIWYG mode using the dropdown after clicking "?" in the bottom-right corner.

**Comment by aroberge** [comment]
My use case for requiring raw html (with custom css) was that I wanted to
include a floating "note".  You can actually see the test one I wrote on
the very first page
https://aroberge.gitbooks.io/reeborg-s-world-advanced-world-creation/content/
 It looks like I want ... but prevents any further edit in the WYSIWYG
mode.

**Comment by AaronO** [comment]
@EDDYMENS Ok just checked your docs (by following your website link in your GitHub profile) and I see you have YouTube videos.

If you used the "plugin syntax" (e.g: `{% youtube %}https://youtube.com/...{% endyoutube %}`) it's the same deal in the current editor.

In the new editor, embeds (youtube videos, ...) are supported first class: https://betadocs.gitbook.com/features/embeds

![image](https://user-images.githubusercontent.com/949223/28596144-7ac4759a-7197-11e7-961c-1fd33d763e40.png)

**Comment by EDDYMENS** [comment]
aaah I see

**Comment by AaronO** [comment]
@aroberge Yeah, putting arbitrary HTML/CSS in your content is "hacky" (we can't support arbitrary in the WYSIWYG, it's just too ambiguous and wouldn't work).

Ideally we should handle all major user-needs first class in the editor.

In the new beta we don't allow inserting arbitrary HTML (because it's a rabbit hole), we do however support rich content 1st-class and can extend it by supporting more types of content.

For your specific use-case, maybe "Hints" might be a good fit: https://betadocs.gitbook.com/features/rich-content#hints-and-callouts

Those are supported out-of-the-box in the new editor, and you get a tailored editing experience:

![image](https://user-images.githubusercontent.com/949223/28596333-4e84b58e-7198-11e7-84c1-8a152038be4e.png)

**Comment by AaronO** [comment]
@EDDYMENS If you're interested in trying out the new beta, send me a quick email at `aaron@gitbook.com`

It seems like it would be a good fit for you since you have a lot of embedded content (YouTube videos and co) in your docs.

**Comment by aroberge** [comment]
Hints and callouts would definitely be acceptable.

I registered for the beta ... hoping that I will not have to wait too long
as I want to finish this book soon - I can work in raw markdown mode, but
the wysiwyg mode is definitely nice to use when embedding screenshots
(which I do a lot).

**Comment by EDDYMENS** [comment]
Nice one will hit you up
