### ISSUE TITLE
Cache issues seems 

### ISSUE THREAD

**Issue by synectiks-code** [GitbookIO/feedback#597]
## Category
Bug

## What is the current behavior?

I update a page , the updated page is not reflected in git book. 
In github it shows updated 
https://github.com/xformation/xformation-book/blob/master/architecture.md
In windows gitbook editor it shows updated.
But published gitbook page --the content is not updated
https://xformation.gitbooks.io/xformation-book/content/architecture.html

I tried  cachec cleaning etc etc, it seems no difference
## What is the desired behavior?

This should be updated
https://xformation.gitbooks.io/xformation-book/content/architecture.html

**Comment by synectiks-code** [comment]
If i go to edit from web explorer , i see latest page , but even i publish , i don't see its reflected in 
https://xformation.gitbooks.io/xformation-book/content/architecture.html

**Comment by AaronO** [comment]
@synectiks-code You can see your builds here: https://www.gitbook.com/book/xformation/xformation-book/activity

And you can see the logs of your latest build here: https://www.gitbook.com/book/xformation/xformation-book/build/5a5877b74f59d5002ef84c44

It seems to fail because you have two fake/incorrect plugins listed in your `book.json`:

```
"plugins": ["toggle-chapters","insert-logo-link", "another plugin 1", "another plugin 2"],
```

(these two: `"another plugin 1", "another plugin 2"`)

---

The new version (https://beta.gitbook.com) that we're shipping in a few weeks, replaces builds with on-the-fly rendering so your content updates can never "fail to build".
It also has 1st class support for branding (header, logo, colors, ...), collapsing chapters, etc ... (so you wouldn't need plugins anymore) with substantial improvements across the rest of the product (editor, ...).
