### ISSUE TITLE
Editor 6 a few suggestions

### ISSUE THREAD

**Issue by popodidi** [GitbookIO/feedback#76]
Hey, I've been using gitbook and gitbook editor recently and  just updated a few versions of new gitbook editor 6. I could see you guys did put a lot of efforts on the version, and I can imagine it would be pretty awesome when it comes to the stable version. Hope some of these suggestions could provide some different points of view for you.
- Update information
  User should be informed at least if it is a beta version or not. I might not be willing to update to a beta version if I'm dealing with something for production rather than just for internal documentation. And there is no way to get back, at least no trivial way as I could see.
- Document mode
  I'm a bit confused of the purpose of this mode. I guess it might be designed to be a normal text editor like Office Word or Apple Pages without need of coding ability. However, I could still code some markdown syntax like "# ", which would make the whole line in header style. On the other hand, the link syntax `[](url)` and inline code syntax is not working, and this is the confusing stuff for me. I expect either all the syntax or none of them should be working, but it is like half half for now.
- Preview mode
  The toolbar in preview mode is hidden for no reason in this version, which was a nice feature in the previous one. I guess you might assume the one who write articles with markdown syntax doesn't need these buttons at all. Unfortunately, I till use some of them from time to time.

**Comment by SamyPesse** [comment]
Hi @popodidi, thank you for the feedback 👍 

1. **Update information**: we considered that this version was mature enough to be released as stable, we have a `beta` and `alpha` channel separated from the `stable` one.

2. **Document mode**: Yes this mode represents the direction we are taking with the GitBook Editor: bring more simplicity and something all users already know how to use.

For now the "document" mode doesn't support inline HTML and templating syntax, so we added a basic raw mode for people using HTML or Templating tags.

But the goal with the upcoming release (`6.x.x`) will be to complete the "document" mode and remove the "raw" mode.

The document mode is very similar to Google Docs, but supports some Markdown shortcuts (`# ` for inserting an heading, `* ` and `1. ` for lists, \`\`\` for code blocks, and `> ` for blockquote)
We will probably add support for more (bold, italic), but links and images might be tricky (I'll run some experimentations).
The goal of these shortcuts is to help pro users stay fast when editing.

3. **Raw mode**: The raw mode can display everything that is a text file (Markdown, Asciidoc, JSON, etc), we didn't added a toolbar for it since we focused our efforts on the "Document" mode. 

Why do you use this mode over the "Document" one? We can potentially add a toolbar back.

**Comment by popodidi** [comment]
Hi @SamyPesse ,

Now I got your ambition 😛. However, if the Gitbook Editor becomes something like Google Docs, I might not be using it. I could understand you're trying to make it easier and more popular, but for me and my colleagues, while I'm not sure if we are the typical users of Gitbook, we use Gitbook for it's conveniency of generating document site and flexibility to manipulate markdown and html syntax. I even made a plugin to add prefix and suffix to my articles. And we manage our files with Gitbook Editor instead of using a markdown editor like MacDown, Sublime Text or Atom and git commands because of its conveniency to manage files like `SUMMARY.md` and `book.json` and  to arrange chapters and consistency of markdown rendering with `$ gitbook build`. So even I am a bit annoyed by the git manipulation of Gitbook Editor, which saves file and commits changes on strange timings, I do use it to edit and manage my books.

In words, personally, I don't need another Google Docs. I need an editor to manage Gitbook files for me. I use raw mode because I prefer more flexibility of editing, which would not be so complicated since it's only markdown syntax.

**Comment by KINGSABRI** [comment]
> For now the "document" mode doesn't support inline HTML and templating syntax, so we added a basic raw mode for people using HTML or Templating tags.
>
> But the goal with the upcoming release (6.x.x) will be to complete the "document" mode and remove the "raw" mode.

That would be sad. One of the main strengths of Gitbook editor is the **raw mode**. 

@SamyPesse please, don't make usability to take over the flexibility. 
For me, I use Gitbook on my daily basis. I've been writing all my technical reports using Gitbook since more than one year

**Comment by ytfei** [comment]
where can i download 5.x.x please, I just cannot get used to 6.x.x without raw mode, why do i need another **Word**

**Comment by bgirardot** [comment]
Is raw mode gone? I have been using GitBook for exactly 15 minutes and I already feel the need for a raw editing mode and went searching for how to enable that and found this issue.

I hope it is not gone and I am just struggling to find it.

**Comment by yycyycyy** [comment]
raw mode is good, document mode is bad.

**Comment by kingsloi** [comment]
I find the document extremely slow (not a hardaware problem) - I have a few gifs in book (application user guide) and it just seems to take a good 10-15 seconds to "load" a document when I navigation from one file to another.

+1 for bring back a toggle for raw/document mode. 

As a hack, I copy in some HTML (A figure tag) which seems to enable raw mode, so that's how I get around it for the time-being.

**Comment by dgreipl** [comment]
Yes, raw mode is needed.

**Comment by bgirardot** [comment]
That should get moved up and out, not buried in a help menu. if you are frustrating my experienced that i have to search for help, that is too late. besides it is not help information, it is toggling a view.

**Comment by nilswald** [comment]
*Toggle raw mode* (aka '*Edit markdown*') belongs in the *View* menu and needs keyboard shortcut support. Maybe make it an individual pane so it can be displayed independently from preview.

**Comment by morinted** [comment]
I think the document mode is great and love that it supports Markdown syntax, however…

Sometimes I want to work in plain text, or write a complicated bit of Markdown that isn't easy to do with GUI tools but trivial with characters. Or, if I want to insert some HTML. It definitely feels like GitBook isn't letting us leverage the power of the technologies behind it while using their desktop editor.

Instead I'll need to use a separate text editor to edit the pages in raw without some raw mode in the GitBook editor.
