### ISSUE TITLE
Can I back to 5. X version?

### ISSUE THREAD

**Issue by mzkmzk** [GitbookIO/feedback#90]
How do I back to 5. X version?

**Comment by longxianlin** [comment]
Same request. 
after updated to 6.x 
cant  sync new content again.

**Comment by longxianlin** [comment]
error  "can't read property 'get Name' of Null"

**Comment by wangbinghuan** [comment]
+1, stuck in loading

**Comment by Soreine** [comment]
We are fixing some bugs related to Syncing.
@wangbinghuan The loading in question is the syncing button loading ? Or does the whole page goes into loading ? 
@longxianlin Do you know if someone is working on the same book and could cause conflicts ?

**Comment by speedornothing** [comment]
Gitbook Editor is a great tool. Thanks for your efforts.  

And, i must say something about the new version (6.x).  
I like using nested list in articles, however, i have been never made the format correctly since upgraded to version 6.x.
I tried to use the non-document mode, but found that the text would disappear occasionally when i enter the 'Enter' or 'Backspace' key, and the 'Undo action' doesn't work.

It would be better if we can download and use the 5.x version temporally.

Thanks again.

**Comment by Soreine** [comment]
After not receiving additional detail, I close this issue since they don't highlight clearly issues that are not duplicate of other issues.

@speedornothing the release history for the Editor is accessible from the download page (or here https://www.gitbook.com/editor/releases), so you can access the full patch notes of each versions.
